server:
  port: 3005

spring:
  application:
    name: cloud-gateway
  zipkin:
    base-url: http://localhost:9411/ # 服务端地址
    sender:
      type: web # 数据传输方式，web 表示以 HTTP 报文的形式向服务端发送数据
  sleuth:
    sampler:
      probability: 1.0 # 收集数据百分比，默认 0.1（10%）

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:3001/eureka/

sleuth:
  web:
    client:
      enabled: true
  sampler:
    probability: 1.0
zuul:
  routes:
    merchant-service:
      path: /merchant/**
  #配置过滤敏感的请求头信息，设置为空就不会过滤
management:
  endpoint:
  endpoints:
    web:
      exposure:
        include: 'routes'
#  sensitive-headers: Cookie,Set-Cookie,Authorization